name: develop-branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        env:
          SENTRY_ORG: podverse
          SENTRY_PROJECT: react
          SENTRY_LOG_LEVEL: debug
          NODE_ENV: development
        run: |
          # TODO: frozen-lockfile was constantly causing actions to fail...
          # maybe it's a good practice but I need to learn how to work with it.
          # yarn install --frozen-lockfile
          yarn install --frozen-lockfile
          yarn lint
          yarn build
          # yarn test:ci

