name: stage-branch

on:
  push:
    branches: [ stage ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install and Check
        env:
          NODE_ENV: development
        run: |
          # TODO: frozen-lockfile was constantly causing actions to fail...
          # maybe it's a good practice but I need to learn how to work with it.
          # yarn install --frozen-lockfile
          yarn install --frozen-lockfile
          yarn lint

      - name: Build
        env:
          SENTRY_ORG: podverse
          SENTRY_PROJECT: react
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          yarn build
          # yarn test:ci

  e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: podverse/podverse_web
        tags: stage

    - name: log into stage, deploy latest stage image, then run e2e tests
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGE_SSH_HOST }}
        username: ${{ secrets.STAGE_SSH_USERNAME }}
        passphrase: ${{ secrets.STAGE_SSH_PASSPHRASE }}
        key: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
        command_timeout: 60m
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use 16.13.1
          docker stop podverse_web_stage
          docker rm podverse_web_stage
          docker image rm podverse/podverse_web:stage
          docker-compose -f /home/mitch/podverse-ops/docker-compose.stage.yml up -d podverse_web
          sleep 60
          cd podverse-ops
          git pull
          cd ../podverse-web
          git pull
          npm install
          npm run test:e2e:suite
